from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path

from common import TERMINAL_STATUSES

# GitHub Actions allows at most 256 jobs generated by one matrix.
MAX_SHARDS = 256


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Pick the next batch of not-yet-migrated videos and emit a "
            "one-video-per-shard matrix for the drip-feed migration cron."
        )
    )
    parser.add_argument("--csv", required=True, help="Source videos.csv")
    parser.add_argument("--log", required=True, help="migration-log.csv")
    parser.add_argument(
        "--count",
        type=int,
        required=True,
        help="How many videos to process this tick (1 job each).",
    )
    return parser.parse_args()


def read_csv(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def main() -> None:
    args = parse_args()
    if args.count < 1:
        raise SystemExit("--count must be >= 1")

    count = min(args.count, MAX_SHARDS)

    source_rows = read_csv(Path(args.csv))
    log_by_id = {
        row["post_id"]: row
        for row in read_csv(Path(args.log))
        if row.get("post_id")
    }

    # Process never-attempted rows first so a persistently failing row never
    # blocks the fresh backlog; only then retry non-terminal rows.
    never: list[int] = []
    retry: list[int] = []
    for index, row in enumerate(source_rows):
        post_id = (row.get("post_id") or "").strip()
        if not post_id:
            continue
        entry = log_by_id.get(post_id)
        if entry is None:
            never.append(index)
            continue
        status = (entry.get("overall_status") or "").strip()
        if status in TERMINAL_STATUSES:
            continue
        if status:
            retry.append(index)
        else:
            never.append(index)

    selected = (never + retry)[:count]
    selected.sort()

    include = [
        {"shard": shard, "start": index, "count": 1}
        for shard, index in enumerate(selected)
    ]

    # Thumbnail payload for the production apply is scoped to this tick's span
    # so it stays small (the receiver rejects payloads over 1000 items).
    if selected:
        sync_start = selected[0]
        sync_limit = selected[-1] - selected[0] + 1
    else:
        sync_start = 0
        sync_limit = 0

    print(
        json.dumps(
            {
                "include": include,
                "sync_start": sync_start,
                "sync_limit": sync_limit,
            },
            separators=(",", ":"),
        )
    )


if __name__ == "__main__":
    main()
